version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    # depends_on:
    #   - redis
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception
    expose:
      - "3306"
    env_file: .env
    restart: always
  
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
      - redis
      - adminer
    build: 
      context: requirements/nginx/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    ports:
      - "443:443"
    env_file: .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    restart: always
    expose:
      - "9000"
    env_file: .env
  
  redis:
    container_name: redis
    image: redis
    build: requirements/bonus/redis/
    depends_on:
      - wordpress
    networks:
      - inception
    expose:
      - "6379"
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    build: requirements/bonus/adminer/
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    restart: always

  ftp:
    container_name: ftp
    image: ftp
    build: requirements/bonus/ftp/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    ports:
      - "0.0.0.0:21:21"
      - "0.0.0.0:20:20"
      - "0.0.0.0:40000-40100:40000-40100"
    restart: always
    env_file: .env

  pelican:
    container_name: pelican
    image: pelican
    build: requirements/bonus/pelican/
    depends_on:
      - website
    volumes:
      - pelican:/md/
    networks:
      - inception
    expose:
      - "8000"
    restart: always

  website:
    container_name: website
    image: website
    build: requirements/bonus/website/
    volumes:
      - pelican:/md/
  
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/user/data/wordpress'
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/user/data/mariadb'

  pelican:
    name: pelican
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/user/data/pelican'

networks:
  inception:
    driver: bridge